[package]
name = "wt_event_handler"
version = "0.1.2"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = true
incremental = true
codegen-units = 4


[dependencies]
scraper = "^0.13.0"
reqwest = "^0.11.10"
tokio = { version = "^1.18.2", features = ['full'] }
serenity = "^0.11.2"
serde = "^1.0.137"
serde_json = "^1.0.81"
log = "^0.4.17"
chrono = "^0.4.19"
lazy_static = "^1.4.0"

[dependencies.log4rs]
version = "^1.1.1"
features = ["file_appender"]

