[package]
name = "wt_event_handler"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
reqwest = "0.11.4"
tokio = { version = "1.8.1", features = ['full'] }
socket2 = "0.4.0"
serenity = "0.10.8"
rand = "0.8.4"
serde = "1.0.126"
serde_json = "1.0.64"
log = "0.4.14"
chrono = "0.4.19"

[target.'cfg(not(windows))'.dependencies]
openssl = "0.10.35"

[dependencies.log4rs]
version = "1.0.0"
features = ["file_appender"]

